//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ الزامی است..
        /// </summary>
        public static string amountRequired {
            get {
                return ResourceManager.GetString("amountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول الزامی است..
        /// </summary>
        public static string codeRequired {
            get {
                return ResourceManager.GetString("codeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد محصول الزامی است..
        /// </summary>
        public static string countRequired {
            get {
                return ResourceManager.GetString("countRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد محصول الزامی است..
        /// </summary>
        public static string feeRequired {
            get {
                return ResourceManager.GetString("feeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه گروه کالا الزامی است..
        /// </summary>
        public static string groupRequired {
            get {
                return ResourceManager.GetString("groupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه محصول الزامی است..
        /// </summary>
        public static string groupTitleRequired {
            get {
                return ResourceManager.GetString("groupTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی نامشخص است(داده ای به سرور ارسال نشده).
        /// </summary>
        public static string InputUnclear {
            get {
                return ResourceManager.GetString("InputUnclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی رخ داده است..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید نامعتبر است..
        /// </summary>
        public static string InvalidPurchase {
            get {
                return ResourceManager.GetString("InvalidPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل الزامی است..
        /// </summary>
        public static string mobileRequired {
            get {
                return ResourceManager.GetString("mobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محصول الزامی است..
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش الزامی است..
        /// </summary>
        public static string orderIdRequired {
            get {
                return ResourceManager.GetString("orderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایند اتصال به سامانه تارا با مشکل مواجه شد..
        /// </summary>
        public static string ProblemConnectingTara {
            get {
                return ResourceManager.GetString("ProblemConnectingTara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست محصولات الزامی است..
        /// </summary>
        public static string productsRequired {
            get {
                return ResourceManager.GetString("productsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های ارسالی نامعتبر هستند.
        /// </summary>
        public static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد محصول الزامی است..
        /// </summary>
        public static string unitRequired {
            get {
                return ResourceManager.GetString("unitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالیات بر ارزش افزوده الزامی است..
        /// </summary>
        public static string vatRequired {
            get {
                return ResourceManager.GetString("vatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای بحرانی وب سرویس.
        /// </summary>
        public static string WebServiceException {
            get {
                return ResourceManager.GetString("WebServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات خطای وب سرویس.
        /// </summary>
        public static string WebServiceExceptionDetail {
            get {
                return ResourceManager.GetString("WebServiceExceptionDetail", resourceCulture);
            }
        }
    }
}
