//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی نامشخص است(داده ای به سرور ارسال نشده).
        /// </summary>
        public static string InputUnclear {
            get {
                return ResourceManager.GetString("InputUnclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی رخ داده است..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید نامعتبر است..
        /// </summary>
        public static string InvalidPurchase {
            get {
                return ResourceManager.GetString("InvalidPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایند اتصال به سامانه تارا با مشکل مواجه شد..
        /// </summary>
        public static string ProblemConnectingTara {
            get {
                return ResourceManager.GetString("ProblemConnectingTara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های ارسالی نامعتبر هستند.
        /// </summary>
        public static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای بحرانی وب سرویس.
        /// </summary>
        public static string WebServiceException {
            get {
                return ResourceManager.GetString("WebServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات خطای وب سرویس.
        /// </summary>
        public static string WebServiceExceptionDetail {
            get {
                return ResourceManager.GetString("WebServiceExceptionDetail", resourceCulture);
            }
        }
    }
}
